import org.gradle.api.publish.maven.MavenPublication
import org.gradle.api.tasks.bundling.Jar
import org.gradle.kotlin.dsl.`maven-publish`

plugins {
    `maven-publish`
    signing
}

publishing {
    // Configure all publications
    publications.withType<MavenPublication> {
        // Stub javadoc.jar artifact
        artifact(tasks.register("${name}JavadocJar", Jar::class) {
            archiveClassifier.set("javadoc")
            archiveAppendix.set(this@withType.name)
        })

        // Provide artifacts information required by Maven Central
        pom {
            name.set("Compose Compiler")
            description.set("Tree composition support for code generated by the Compose compiler plugin and corresponding public API")
            url.set("https://android.googlesource.com/platform/frameworks/support/+/androidx-main/compose/runtime")

            licenses {
                license {
                    name.set("Apache-2.0")
                    url.set("https://www.apache.org/licenses/LICENSE-2.0.txt")
                }
            }
            developers {
                developer {
                    id.set("Google")
                    name.set("Google Android Team")
                    organization.set("Google LLC")
                    organizationUrl.set("https://www.google.com")
                }
            }
            scm {
                url.set("https://android.googlesource.com/platform/frameworks/support/+/androidx-main/compose/runtime")
            }
        }
    }
}

signing {
    if (project.hasProperty("signing.gnupg.keyName")) {
        useGpgCmd()
        sign(publishing.publications)
    }
}
